# Generated by Django 5.1.4 on 2024-12-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('studName', models.CharField(max_length=50)),
                ('division', models.CharField(max_length=20)),
                ('rollNo', models.CharField(max_length=10, unique=True)),
                ('phone', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'school',
            },
        ),
    ]
