let intro=document.getElementById('intro')
// intro.parentElement.textContent='hello'

// intro.nextElementSibling.nextElementSibling.innerHTML='dog'

// let wrapper=document.querySelector('.wrapper')
// let div=document.createElement('div')
// div.className='content'
// let doc=document.createElement('h1')
// doc.className='head'
// doc.textContent='This create element tag'
// div.append(doc)
// wrapper.appendChild(div)


// window.addEventListener('scroll',function(){
//     if(window.pageYOffset>150){
//         console.log('sccroll up')
//     } else{
//         console.log('scroll down'); 
//     }
// })



