# Generated by Django 5.1.4 on 2024-12-23 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='emp',
        ),
    ]
